app = 'omre-asc-mcp'
primary_region = 'lhr'

[build]

[env]
  AMAZON_MCP_HOST = "0.0.0.0"
  AMAZON_MCP_PORT = "8080"
  AMAZON_MCP_TRANSPORT = "streamable-http"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1